### ISSUE TITLE
Req: Backward compatibility

### ISSUE THREAD

**Issue by cachapa** [JakeWharton/salvage#1]
It's a good idea, but the current implementation requires API >= 14.
I just tried it on Android 2.3, and got a
java.lang.NoSuchMethodError: android.view.View.setAccessibilityDelegate

I'd be interested in giving it another go, if backward compatibility is in the plans for the future :-)

**Comment by JakeWharton** [comment]
Ah, yeah. That's easily abstracted behind a version check. I'm not sure why I didn't just outright delete those method calls.

**Comment by JakeWharton** [comment]
Fixed on `master`.
